### ISSUE TITLE
Task 'assembleGvrRelease' not found in root project 'myviroapp'. Some candidates are: 'assembleRelease'.

### ISSUE THREAD

**Issue by rogers-dwiputra** [ViroCommunity/starter-kit#1]
Hi, i'm trying to run this starter kit, after `npm install`, I execute `./gradlew assembleGvrRelease` inside android directory, but resulting this error :

`Task 'assembleGvrRelease' not found in root project 'myviroapp'. Some candidates are: 'assembleRelease'.`

Thank You

**Comment by doranteseduardo** [comment]
Indeed, I'm sorry for the inconveniences of haven't added documentation yet.

The way I linked the android side rendered useless the use of Viro variants, specially as I noticed they were pointing to the same configuration.

You can use assembleRelease normally, as well as avoiding the variant parameter while testing. 

Best regards.

**Comment by rogers-dwiputra** [comment]
Hi @doranteseduardo thanks for provide the documentation, however, I have a problem when running `npx react-native run-android` here is the result :

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-viro.
     Required by:
         project :app
      > No matching configuration of project :react-viro was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.
```

I use `node v14.15.4` and `npm 7.4.0` with `M1 Processor`

**Comment by rogers-dwiputra** [comment]
Hi, so the issue is my M1 Processor, it work on my windows PC, so I guess this issue is solved
