### ISSUE TITLE
Has both yarn.lock and package-lock.json

### ISSUE THREAD

**Issue by equationalapplications** [ViroCommunity/starter-kit#23]
Is 'npm install' still the preferred way to install? Is it a problem to include the yarn.lock as well?

**Comment by NS-BOBBY-C** [comment]
Closing since both package-lock.json and yarn.lock were removed. Either way works perfectly fine!

See e7ede555e71e7b9c2494900c5c573c82223d0618 and d989aea53a33ce8a7b7864331bf72cf6c6d476e2 for more.
