### ISSUE TITLE
for run on win

### ISSUE THREAD

**Issue by tarnamaco** [ViroCommunity/starter-kit#27]
Hi guys
I cloned the starter kit and faced problems, after some clone loop (!), fixed.

- In win32 and android development, there is no fsevents, so remove from package.json
- in package.json set react and react-native with ^ sign version "^17.0.2", "^0.65.2"
and "npm upgrade".
hope useful

**Comment by firstChairCoder** [comment]
Thanks a lot.

**Comment by NS-BOBBY-C** [comment]
@tarnamaco @firstChairCoder running on windows - react native and read need to be upgraded here?
