### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by SilverOcJu** [ViroCommunity/starter-kit#36]
Getting this error on Metro when running the "starter-kit" on an Android Device 

`
ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[4], "@viro-community/react-viro").ViroConstants.TRACKING_NORMAL')
`
Any help? The app also turns to an screen with the same error

**Comment by Jexim** [comment]
@SilverOcJu look at this [answer](https://github.com/ViroCommunity/starter-kit/issues/34#issuecomment-1084173573).

**Comment by SilverOcJu** [comment]
Thank you, @Jexim ! It's working now
