### ISSUE TITLE
undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[4], "@viro-community/react-viro").ViroConstants.TRACKING_NORMAL')

### ISSUE THREAD

**Issue by Sunil-prajapati** [ViroCommunity/starter-kit#37]
Hello 

I am simply trying to run starter-kit app with follow all the given steps
 
env:
"@viro-community/react-viro": "^2.20.2",
"react": "17.0.2",
"react-native": "0.65.1"

xcode version: Version 13.3.1

after pod install just add team id for debug build and rest of the things are same but i don't why it is happening

**Comment by kaleong912** [comment]
Hi, I encountered the exactly same issue, may I know how to solve this problem?
I will be grateful if any help you can provide!

**Comment by Priya20417** [comment]
Hello, I am facing the same error(TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[4], "@viro-community/react-viro").ViroConstants.TRACKING_NORMAL')).it would be really helpful, if you can provide any solution
