### ISSUE TITLE
Error occur at npm install step.

### ISSUE THREAD

**Issue by chokchaiph** [ViroCommunity/starter-kit#49]
I found the errors at step npm install node module.
![errors](https://user-images.githubusercontent.com/17692846/184476387-cd38ceaf-f242-42af-9600-c4436552f93e.png)
.

**Comment by chokchaiph** [comment]
I did as npm recommended by flag --legacy-peer-deps then it's works.

**Comment by Mustafadagkiranlar** [comment]
You can edit package.json file where devDependencies and find "eslint" change version to ">=8" it fixed my problem.
