### ISSUE TITLE
3d Models don't work

### ISSUE THREAD

**Issue by marcofugaro** [ViroCommunity/starter-kit#5]
I am following [this tutorial here](https://dev.to/peterklingelhofer/an-introduction-to-augmented-reality-with-viro-1nf4)

I've added the following code inside the `ViroARScene` 

```js
<Viro3DObject
  source={require('./res/emoji_smile/emoji_smile.vrx')}
  position={[0, 0, -1]}
  scale={[.2, .2, .2]}
  type="VRX"
  dragType="FixedDistance" onDrag={()=>{}} // allows user to drag 3D object around with finger
/>
```

And I've added the relative file in my project (`res` folder and I'm sure the full path exists `/res/emoji_smile/emoji_smile.vrx`).

But this error happens

![image](https://user-images.githubusercontent.com/7217420/112292767-b8974500-8c91-11eb-8a7a-7f82d8b5c6e3.png)

I tried also with other files (.glb would be my ideal solution), but nothing works.

**Comment by mariansam** [comment]
Hi, thanks for using ViroReact! I've had the same problem and I found out that the Metro packager by default does not allow `require`ing files with the `.obj`, `.vrx`, etc. extensions. I'm gonna open a PR today with the correct Metro configuration.

**Comment by mariansam** [comment]
I just opened #6. If you want your code to work right now, add the code below to the file `metro.config.js` in your project.
```ts
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { assetExts }
  } = await getDefaultConfig();

  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      }),
    },
    resolver: {
      assetExts: [...assetExts, "obj", "mtl", "JPG", "vrx", "hdr", "gltf", "glb", "bin", "arobject", "gif"]
    }
  }
})();
```
