### ISSUE TITLE
In HelloWorldSceneAR when change fontSize to more than 43 texts just show the first word

### ISSUE THREAD

**Issue by ako-v** [ViroCommunity/starter-kit#9]
In HelloWorldSceneAR when change fontSize to more than 43, it just shows the first word (Initializing or hello).
Even if you change scale or position to make text smaller it does not show the whole text, but just first word.

**Comment by doranteseduardo** [comment]
The Text component accepts a width and height attributes, you can adjuste it for all of your text to fit.
